### ISSUE TITLE
Reference to /Users/Gustavo/Documents/VALET/Antvel/Shop makes the app squeak 

### ISSUE THREAD

**Issue by wander112900** [ant-vel/App#11]
OS: Centos6.6
antvel install

                                                                                                 
  [RuntimeException]                                                                             
  Source path "/Users/Gustavo/Documents/VALET/Antvel/Shop" is not found for package antvel/shop

**Comment by gocanto** [comment]
I gotta look into it. I have no idea why you have references for that folder. I will be back with you!

**Comment by gocanto** [comment]
Can you try to remove your composer.lock? 

if you see, there is a reference here https://github.com/ant-vel/App/blob/master/composer.lock#L15 to that route. This is due to the heavily use of this project in development mode. 

So, you can try to remove that file, remove your vendor folder and run ```composer install```.

Let me know how it goes while I am still looking for a better way to keep this from happening. 

thanks for testing.

**Comment by gocanto** [comment]
It should be fixed in this commit https://github.com/ant-vel/App/commit/36f1f8cbeb3654ef6bd4b97c352cab816c9b7400

Take a look at the composer.lock file.

Let me know please!
