### ISSUE TITLE
Read.me file wrong info?

### ISSUE THREAD

**Issue by nezaboravi** [ant-vel/App#41]
Hi
At read me file there is a link to app as well as user/pass
None of user/pass works for a given link, so i suppose this is not a 'demo' link and user/pass are for local dev initial users?

Link to contribute on readme page leads to 404.

Regards

**Comment by gocanto** [comment]
The online app has different credentials from those. Reason why is stupid people started posting porn info in the store.

**Comment by bloggervista** [comment]
@gocanto  we can create artisan reset command to reset that password hourly. Will be happy to PR it if you agree.
And fuck those people who pollute such things to opensource

And how about making this package laravel 5.5 because many things are not 5.5. like it use gulp bower instead of webpack i.e Laravel mix.

**Comment by gocanto** [comment]
I would not like to spend time just for having the app running with those credentials. Also, I would not have the time to keep up with the app management. 

PR's are welcome as always for bugs, features, etc. 

for features, we can discuss before. 

Also, Antvel is laravel 5.5 fully compatible. 

Thanksn.
